name:                Day18
version:             0.1.0.0
github:              "cronin10/AdventOfCode"
license:             BSD3
author:              "Aaron Cronin"
maintainer:          "cronin@include.cat"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cronin10/Day18#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring

library:
  source-dirs: src

executables:
  Day18-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day18

tests:
  Day18-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day18
