name:                AoCUtils
version:             0.1.0.0
github:              "cronin101/AdventOfCode"
license:             MIT
author:              "Aaron Cronin"
maintainer:          "cronin@include.cat"
copyright:           "2020 Aaron Cronin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2020-utils#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring

library:
  source-dirs: src

tests:
  aoc2020-utils-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020-utils
